id: P784704D2
initial_creation_type: input
source_metadata:
  title: Shechen Rabjam Rinpoche Series
  language: de
  description: 'Texts by and about Jigme Chökyi Senge (''jigs med chos kyi seng+ge,
    b. 1966), the seventh Rabjam Rinpoche of Shechen Monastery:'
  volume:
    b8de4985582a4090953cba7684a70585:
      title: Calling the Guru from Afar
      parent: Calling the Guru from Afar
    301f4378b93249b59be5f34ad9fbc7f1:
      title: A Supplication for the Longevity of the Peerless and Sublime Tulku, Dzongsar
        Khyentse, Thupten Chökyi Gyatso
      parent: Long Life Prayers
    d56f6dd0322443609d4a1b6375ea8cb6:
      title: Prayer for the Long Life of Shechen Rabjam Rinpoche
      parent: Long Life Prayers
    d4876e69b54247c18d49bfaa87a6a30a:
      title: A Prayer to Kyabje Dilgo Khyentse Rinpoche
      parent: Prayers
    48e412f11df44b959d26a6facb82931c:
      title: 'The Beat of the Vajra Drum: A Prayer'
      parent: Prayers
    f294e1ff3ba2405fa19ba4840dc23a39:
      title: 'The Lotus of Faith: A Supplication to the Successive Lives of Shechen
        Rabjam'
      parent: Prayers
    46d1e2a2c585447ab5b6d93e1a47dc47:
      title: 'The Potent Nectar of Accomplishment: A Prayer and Supplication to the
        Vidyādhara Gurus of the Three Lineages'
      parent: Prayers
    cb7e51faa4b54be9866f4dac9648064b:
      title: A Prayer for the Swift Return of the Fourth Kyabje Dodrupchen Rinpoche
      parent: Swift Rebirth Prayers
created_at: '2022-03-01T01:35:58.832616'
last_modified_at: '2022-03-01T01:35:58.832619'
